In [2]:
#ARRAY SHAPE AND RESHAPE
import numpy as np

In [6]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)

(2, 3)
2
6


In [18]:
ar=np.array([1,2,3,4,5,6,7,8,9,10,11,12])


In [17]:
res=ar.reshape(2,6)
res

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [20]:
s=ar.reshape(2,2,-1) 
s

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
s2=ar.reshape(1,1,-12)
s2

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]])

In [30]:
for i in ar:
    print(i,end=" ")


1 2 3 4 5 6 7 8 9 10 11 12 

In [31]:
arr2=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [34]:
for i in np.nditer(arr2):
    print(i)


1
2
3
4
5
6
7
8
9
10
11
12


In [36]:
sinarr=np.sin(arr2)
sinarr

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
        -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849, -0.54402111, -0.99999021,
        -0.53657292]])

In [39]:
matrix_a=np.array([[2,4],[6,3]])
matrix_b=np.array([[1,2],[6,5]])
result=np.dot(matrix_a,matrix_b)
result


array([[26, 24],
       [24, 27]])